name: habbit_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.7
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.5

flutter_native_splash:
  background_image: "assets/images/splash_image.png"
  android: true
  ios: true
  android_gravity: center
  ios+content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/auth/

  fonts:
    - family: Klasik
      fonts:
        - asset: assets/fonts/Klasik Regular.otf
